@startuml

skinparam actorStyle hollow

actor        "Practitioner"     as pra
actor        "Patient"          as pat
participant  "FHIR API"         as api
entity       "Consent"          as con
entity       "Patient Flag"     as flg
entity       "Adjustment Flag"  as adj
entity       "Condition"        as cod

pra ->  pat : Examine patient
pra ->  pat : Suggest adjustments
pra <-- pat : Provide consent\nto share information

pra ->  api : Record adjustment record (transaction Bundle)

api ->  con : Create/update resource
con ->  con : Validate
api <-- con : return
alt Validation failed
  api -> api : rollback
end

api ->  flg : Create/update resource
flg ->  flg : Validate
api <-- flg : return
alt Validation failed
  api -> api : rollback
end

api ->  adj : Create/update resource
adj ->  adj : Validate
api <-- adj : return
alt Validation failed
  api -> api : rollback
end

alt Condition also to be recorded
api ->  cod : Create/update resource
cod ->  cod : Validate
api <-- cod : return
alt Validation failed
  api -> api : rollback
end
pra <-- api : OperationOutcome

@enduml

