@startuml

|<font color=gray><b><u>Practioner</u></b></font>|
start
:Request consent;

|#LightGray|<font color=gray><b><u>Patient</u></b></font>|
if (Capacity to\n  consent?) is (Yes) then
:Provide consent; 
else (No)

|<font color=gray><b><u>Patient Advocate</u></b></font>|
:Provide consent; 
endif

|<font color=gray><b><u>Practioner</u></b></font>|
if (Consent given) is (Yes) then
:Record/confirm\n consent given;
else (No)
:    Revoke consent\nand previous records;
endif

|#LightGray|<font color=gray><b><u>API</u></b></font>|
:Update API;
note right
There are vaious
ways this can be
acheived and 
examples are 
provided 
throughout
end note

|<font color=gray><b><u>Practioner</u></b></font>|
:Confirmation;
stop

@enduml