@startuml

skinparam linetype ortho

entity "Patient" as pat {
  *NHS Number : number <<generated>>
}

entity "Consent" as con {
  *patient : Patient
  *category : CodeableConcept
  *contained : Provenance (Contained)
}

entity "Condition" as cod {
  *patient : Patient
  *code : CodeableConcept
  *category : CodeableConcept
  *contained : Provenance (Contained)
}

entity "Patient Flag" as pfg {
  *patient : Patient
  *code : CodeableConcept
  *category : CodeableConcept
  *contained : Provenance (Contained)
}

entity "Adjustment Flag" as adj {
  *patient : Patient
  *code : CodeableConcept
  *category : CodeableConcept
  *contained : Provenance (Contained)
}

entity "Provenance" as pro {
  *recorded : Date
  *agent : Agent (backbone)
}

pat ||..|| con : provides
pat ||--o{ cod : has
pat ||--o| pfg : "has"
pat ||--o{ adj : has
con ||--|| pro : contains
cod ||--|| pro : contains
pfg ||--|| pro : contains
adj ||--|| pro : contains

@enduml
