@startuml

skinparam linetype ortho

entity "Patient" as pat {
  *NHS Number : number <<generated>>
}
package "Patient Flags API" {

entity "Patient Flag" as pfg {
  *patient : Patient
  *code : CodeableConcept
  *category : CodeableConcept
  *contained : Provenance (Contained)
}

package "Additional Detail" {

entity "Consent" as con {
  *patient : Patient
  *category : CodeableConcept
  *contained : Provenance (Contained)
}

entity "Condition" as cod {
  *patient : Patient
  *code : CodeableConcept
  *category : CodeableConcept
  *contained : Provenance (Contained)
}

entity "Programme Flag" as prfg {
  *patient : Patient
  *code : CodeableConcept
  *category : CodeableConcept
  *contained : Provenance (Contained)
}

entity "Provenance" as prov {
  *recorded : Date
  *agent : Agent (backbone)
}
}
}

pat ||..|| con : provides
pat ||--o{ cod : has
pat ||--o| pfg : has
pat ||--o{ prfg : has
con ||--|| prov : contains
cod ||--|| prov : contains
pfg ||--|| prov : contains
prfg ||--|| prov : contains
pfg ||..o{ prfg : details

@enduml
