@startuml

skinparam actorStyle hollow

actor        "Patient"          as pat
actor        "Practitioner"     as pra
boundary     "FHIR API"         as api
entity       "Additional Detail\n(Condition)"  as add

  pat ->  pra : Remove
  pra ->  api : Remove
  api ->  add : Remove resourc
  
  add ->  add : Validate
  api <-- add : return
  alt Validation failed
    api -> api : rollback
  end

pra <-- api : OperationOutcome

@enduml
