@startuml

skinparam actorStyle awesome

actor Practitioner as pra
package Consenter {
  actor "Patient Advocate" as pad
  actor Patient as pat
}

usecase  "Consent not granted" as CNG
usecase "Remove Reasonable Adjustment record" as RET

pat -- CNG
pad -- CNG
pra -- RET
CNG -- RET


@enduml
