@startuml

skinparam actorStyle hollow

actor        "Practitioner"     as pra
participant  "FHIR API"         as api
entity       "Patient Flag"     as pfg
entity       "Adjustment Flag"  as adj
entity       "Condition"        as cod

  pra ->  api : Query for records

      api -> pfg : Query for records
      api -> adj : Query for records
      api -> cod : Query for records

  api ->  api : Assemble returns
  pra <-- api : SearchSet Bundle


@enduml